### PR TITLE
simple fix for patient portal

### PR DESCRIPTION
**Pull request by stephenwaite**
hi @jesdynf , think this is the fix to get the patient portal to work

### CODE REVIEW

**Comment by stephenwaite** [comment]
sorry for the extra commits, just trying to clean up white space :|

**Comment by bradymiller** [comment]
Hi @stephenwaite ,
Is the patient portal broken in 5.0.1 docker or 5.0.2 docker or both?
-brady

**Comment by stephenwaite** [comment]
i believe just 5.0.1 so assumed 5.0.2 since it's the same openemr.conf

**Comment by bradymiller** [comment]
Very odd, since I tested this a long time ago (when released 5.0.1) on the dockers. The one funny thing about the portal is that you can't have a portal session and openemr session open at the same time on the same web browser. Hopefully this is the issue. Does this fix issue? (ie. try the portal on a separate web browser where there is no active openemr session)

**Comment by stephenwaite** [comment]
nope, i've got the emr running in firefox and the portal in chrome

**Comment by bradymiller** [comment]
hi @stephenwaite ,

I just tested this on both the 5.0.1 and 5.0.2 example dockers (running on play with dockers site), and the portal appears to be working fine:
https://community.open-emr.org/t/openemr-official-docker-has-been-released/9084/10

Anything specific that is broken on your testing?

-brady

**Comment by stephenwaite** [comment]
hi @bradymiller , maybe it's related to setting up let's encrypt with aws? 
i followed the instructions here, 
`cd /root/openemr-devops/packages/lightsail
# edit docker-compose.yml: add environment variables DOMAIN and EMAIL to the openemr container
./docker-compose up -d`

**Comment by stephenwaite** [comment]
it seems to be fixed when you change the 

> Version 2 Onsite Patient Portal Site Address

to just `/portal` vs `/openemr/portal`

**Comment by stephenwaite** [comment]
after all of the discussion on the forum thinking this is a non-issue?
https://community.open-emr.org/t/portal-v2-registration-never-goes-to-step-2/11152/8

**Comment by bradymiller** [comment]
agreed

**Comment by bradymiller** [comment]
Best to avoid using alias, if possible. Otherwise it seems to break use of the standard .htaccess files in patient portal, zend, and the future api.

**Comment by stephenwaite** [comment]
OK, thanks Brady

**Pull request closed without merging**
