### PR TITLE
Open Collective banner

### PR DESCRIPTION
**Pull request by MatthewVita**
Preview:
```
Generating a 4096 bit RSA private key
........................................................................................................................++
............++
writing new private key to '/etc/ssl/private/selfsigned.key.pem'
-----

Love OpenEMR? You can now support the project via the open collective:
 > https://opencollective.com/openemr/donate

Starting cron daemon!
Starting apache!
```

### CODE REVIEW

**Comment by MatthewVita** [comment]
(If this passes code review, which I think it will :), I'll put in a PR to update the still-in-beta OpenEMR Local Development Docker in the main repo)

**Comment by MatthewVita** [comment]
Thanks @jesdynf 

Will wait on @bradymiller

**Comment by MatthewVita** [comment]
Thanks guys.

@bradymiller can you give me permissions to push to docker hub: https://hub.docker.com/u/matthewvita/

**Comment by bradymiller** [comment]
@MatthewVita , just set you up as a owner for docker openemr org. Let me know if you have any issues pushing the new dockers.

**Comment by MatthewVita** [comment]
Thanks!

**Pull request merged**
