### PR TITLE
Update docker shell access

### PR DESCRIPTION
**Pull request by JXPrime**
sudo is needed in both instances of the docker command (I cut and paste this all the time lol)

### CODE REVIEW

**Comment by JXPrime** [comment]
That's a bit beyond mu linux-fu. the other option that I can think of is to
do sudo -i and then the rest of the command?

**Comment by jesdynf** [comment]
I think I got it--

`sudo -i -- sh -c 'docker exec -it $(docker ps | grep _openemr | cut -f 1 -d " ") /bin/sh'`

Can you update to pick that up?

**Comment by JXPrime** [comment]
Oh brilliant! I have so much to learn still. Thanks!

**Comment by jesdynf** [comment]
Hey, thanks for the improvement!

**Pull request merged**
