### PR TITLE
Fixing email detection

### PR DESCRIPTION
**Pull request by TheToolbox**
Fixes inverted warning for no $EMAIL when $DOMAIN is set, and fixes a bug causing LE to fail in that same scenario.

### CODE REVIEW

**Comment by TheToolbox** [comment]
Okay a bit confused (probably just tired). I accidentally included the "apk --update" commit from the apache-ssl fix, whcih I figured was no big deal, given that I was going to squash them anyway. Why is github showing those as changed files with respect to master? I just double-checked that master has those lines in it. Am I missing something?

**Comment by jesdynf** [comment]
I saw that and I don't get it either, but the commit seems fine. Let's wait on Travis, though.

**Comment by TheToolbox** [comment]
Travis is good, bringing it in (with hopefully no issues...)

**Comment by bradymiller** [comment]
@TheToolbox , I just updated all the dockers and pushed them to docker hub :)

**Pull request merged**
