### PR TITLE
Specify current docker image

### PR DESCRIPTION
**Pull request by surfacehazard**
Specify current docker image used so it can be overridden.

Fixes #

#### Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by jesdynf** [comment]
I'm not sure I understand the issue. The `-t` option accepts an override image, which gets sed-replaced into the file if necessary during .yml selection in lines 81-111, and I don't know why `7.0.2` would work if `latest` doesn't. Is there a problem with that logic I'm not aware of?

**Comment by surfacehazard** [comment]
sed won't replace anything - there is no openemr:latest in the docker-compose files

**Comment by jesdynf** [comment]
:tantrum follows:

**Comment by jesdynf** [comment]
I set this to :latest so I wouldn't have to keep catching it up, and I can't *just* change the dependencies to latest because some of them, the dev ones, actually honestly do have to hardcode 7.0.2, so you're right, this was the only option. Thanks for catching this!

**Pull request merged**
