### PR TITLE
Added the flex docker

### PR DESCRIPTION
**Pull request by bradymiller**
@TheToolbox and @jesdynf ,

I've been wanting to do this for awhile. This basically rolls a openemr docker from any public git respository. See here for more details:
https://community.open-emr.org/t/openemr-official-docker-has-been-released/9084/9

-brady

### CODE REVIEW

**Comment by TheToolbox** [comment]
I'm not quite sure what the benefit of this strategy might be over letting dev users do what would normally be done, either setting up a docker-compose config to build and run stuff (easiest), or do the clone themselves and run `docker build myRepo --tag=myImage && docker run myImage`

**Comment by TheToolbox** [comment]
If the goal is to keep the flex branch in sync with master, then I think what groups normally do is set up automated build and push to Docker hub, since much of the goal of a docker image in the first place is to freeze the code and make it predictable. This setup would clone on the first creation of a container, and update each time the container was recreated.

**Comment by MatthewVita** [comment]
I like it!

**Comment by TheToolbox** [comment]
Okie Dokes!

**Comment by bradymiller** [comment]
whoohooo, flex is official :)
thanks @TheToolbox 
next planned openemr docker and tag is attain.world.peace :)

**Pull request merged**
