### PR TITLE
addresses #161, rotate apache logs

### PR DESCRIPTION
**Pull request by stephenwaite**

### CODE REVIEW

**Comment by stephenwaite** [comment]
for #161 , hopefully this is the right dockerfile :)

**Comment by jesdynf** [comment]
Should be, but I noticed certbot is making the build fail right now.

```
Obtaining file:///opt/certbot/acme
Obtaining file:///opt/certbot
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/opt/certbot/setup.py'"'"'; __file__='"'"'/opt/certbot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /opt/certbot/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/certbot/setup.py", line 61, in <module>
        if StrictVersion(setuptools_version) >= StrictVersion('36.2'):
      File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
        self.parse(vstring)
      File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
        raise ValueError, "invalid version number '%s'" % vstring
    ValueError: invalid version number '39.1.0.post20180508'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c mkdir -p /var/www/localhost/htdocs/openemr/sites     && chown -R apache /var/www/localhost/htdocs/openemr     && git clone https://github.com/letsencrypt/letsencrypt /opt/certbot     && pip install --upgrade pip     && pip install -e /opt/certbot/acme -e /opt/certbot     && mkdir -p /etc/ssl/certs /etc/ssl/private' returned a non-zero code: 1
```

**Comment by stephenwaite** [comment]
hi @jesdynf , shouldn't the travis log have rel-502 and match the dockerfile details like 
`    && git clone https://github.com/letsencrypt/letsencrypt --branch 0.35.x --depth 1 /opt/certbot `

**Comment by stephenwaite** [comment]
this is failing,  https://github.com/openemr/openemr-devops/blob/276ebdcbf71d2481049597f86aec6ea5e3875f68/docker/mysql-xtrabackup/Dockerfile#L45, not sure if this important

**Comment by bradymiller** [comment]
ouch, this is going to require some good testing. Seeing bunch of issues related to both logrotate and openrc. Suggest closing this PR and continuing discussion on related issue.

**Comment by stephenwaite** [comment]
ok, thank you @bradymiller

**Pull request closed without merging**
