### PR TITLE
edits by Rod and Stephen

### PR DESCRIPTION
**Pull request by stephenwaite**
hope this helps a little

### CODE REVIEW

**Comment by jesdynf** [comment]
It does! But I'll have to manually copy it into my parallel PR and close this one, though, because I am a git scrub.

**Comment by stephenwaite** [comment]
great, enjoying your work very much, kudos

**Comment by jesdynf** [comment]
Thanks a lot!

**Comment by MatthewVita** [comment]
Great to see the teamwork here guys

**Pull request closed without merging**
