### PR TITLE
sql drive integrate with some other stuff

### PR DESCRIPTION
**Pull request by bradymiller**
Mostly to integrate stuff by @boxlady for sql importing also with some other changes. Will point out where integrated the sql importing in a post above.

Still need to test this out.

### CODE REVIEW

**Comment by bradymiller** [comment]
@boxlady ,
Let me know how this works in your workflow.

On  new docker-compose up, here is where it will bring in the sql data (if set the SQL_DATA_DRIVE variable to the path):
https://github.com/openemr/openemr-devops/blob/a22c3ac4f63d095cef61c5a00521b854a901e5ad/docker/openemr/flex-3.12/autoconfig.sh#L51-L53
the function for this is here:
https://github.com/openemr/openemr-devops/blob/a22c3ac4f63d095cef61c5a00521b854a901e5ad/docker/openemr/6.0.0/utilities/devtoolsLibrary.source#L80-L88

And after the docker load-up, can then bring in the data via the following functions in devtools:
https://github.com/openemr/openemr-devops/blob/a22c3ac4f63d095cef61c5a00521b854a901e5ad/docker/openemr/flex-3.12/utilities/devtools#L129
https://github.com/openemr/openemr-devops/blob/a22c3ac4f63d095cef61c5a00521b854a901e5ad/docker/openemr/flex-3.12/utilities/devtools#L139

**Comment by bradymiller** [comment]
Got a bit carried away and also just added a backup/restore feature to this PR (pretty much unrelated to this PR :) ). It will allow taking a "snapshot" of openemr.
```
docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c '/root/devtools backup example'
```
This basically backs up the database/filesystem(`sites/*`) in a snapshot called `example`.
Can then restore to the `example` snapshot via:
```
docker exec -i $(docker ps | grep _openemr | cut -f 1 -d " ") sh -c '/root/devtools restore example'
```

**Comment by bradymiller** [comment]
Is all testing well. Got 3 new features in here:
1. The sql data drive feature. Just set `SQL_DATA_DRIVE` environment to a path and it will load all the .sql files from it when doing a docker-compose up (it does it after the auto-installation stuff). User can also run the imports via the devtools (`dev-reset-sqldrive`, `dev-reset-install-sqldrive`, `dev-reset-install-demodata-sqldrive`).
2. A new environment setting `DEMO_MODE`. If this is set to `standard`, then when doing docker-compose up, it will bring in all the standard demo data.
3. Two new devtools, which basically allow creating snapshots of OpenEMR (the data and sites/ dir; not not meant for codebase changes, but meant for the OpenEMR data), via `backup <identifier>' and `restore <identifier>`. So, for a example, a developer could make the backup point, do something that horribly messes up something in the install, and then do a restore to go back.

**Comment by bradymiller** [comment]
Gonna bring this in and update dockers.

**Comment by boxlady** [comment]
> Is all testing well. Got 3 new features in here:
> 
> 1. The sql data drive feature. Just set `SQL_DATA_DRIVE` environment to a path and it will load all the .sql files from it when doing a docker-compose up (it does it after the auto-installation stuff). User can also run the imports via the devtools (`dev-sqldrive`, `dev-reset-install-sqldrive`, `dev-reset-install-demodata-sqldrive`).

This makes testing with data easy peese. 

> 2. A new environment setting `DEMO_MODE`. If this is set to `standard`, then when doing docker-compose up, it will bring in all the standard demo data.

> 3. Two new devtools, which basically allow creating snapshots of OpenEMR (the data and sites/ dir; not not meant for codebase changes, but meant for the OpenEMR data), via `backup <identifier>`and `restore <identifier>`. So, for a example, a developer could make the backup point, do something that horribly messes up something in the install, and then do a restore to go back.

This is awesome! Thank you so much. This makes my life so much easier!

**Comment by jesdynf** [comment]
This is really nice.

**Comment by bradymiller** [comment]
I am forgetting the name of snapshots that I created, so there will soon be another devtool called `list-snapshots` :)
(rather than having to manually look at the directories in /root/backup/ )

**Comment by bradymiller** [comment]
`list-snapshots` devtool is now official :)
https://github.com/openemr/openemr-devops/commit/1d7fc99fc1cc20145ba8d6630db540043abc9618

**Pull request merged**
