### PR TITLE
docs: fix chat link and update all links to https

### PR DESCRIPTION
**Pull request by stu01509**
Fix chats link and update all links to https.

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @stu01509 , It looks like all the play-with-docker.com links need to be http. Using the https links for them doesn't work.

**Comment by stu01509** [comment]
Hi @bradymiller 

Thanks for your noticed, I will fix it 🙂

**Comment by stu01509** [comment]
Hello @bradymiller 

I updated commit, Please review it again.

**Comment by bradymiller** [comment]
hi @stu01509 , Changes look good and bringing in. Thanks for the fixes! -brady

**Pull request merged**
