### PR TITLE
goal to remove dependence on pip in flex-edge and re-offer support for linux/arm/v7

### PR DESCRIPTION
**Pull request by bradymiller**
goal to remove dependence on pip in flex-edge and re-offer support for linux/arm/v7

### CODE REVIEW

**Comment by bradymiller** [comment]
fingers crossed that we get arm/v7 back :) (and that we do not break certbot :) )
@jesdynf

**Comment by bradymiller** [comment]
woohoooo, linux/arm/v7 is back!
https://hub.docker.com/r/openemr/openemr/tags
(`flex-edge` tag)

Now just gotta prove that not breaking certbot. gonna bring these changes into 7.0.2 for now and hopefully @stephenwaite will then know how to test that :)

**Comment by jesdynf** [comment]
That's amazing. Glad to get it back.

**Comment by bradymiller** [comment]
7.0.2/dev docker is also working for linux/arm/v7 :)

Next up is the flex docker series and then back to 7.0.1 (when do next 7.0.1 patch) after confirm that certbot is working.

**Comment by bradymiller** [comment]
After confirm that certbot is working fine in 7.0.2, then can bring this in for the flex and 7.0.1 dockers:
#369

**Pull request merged**
