### PR TITLE
Fix for missing zlib php extension

### LINKED ISSUE #57: Administration->Backup is broken in docker
@TheToolbox , @jesdynf 

Getting the following error:
Abort backup.php : Missing zlib extensions

(confirmed this bug in both the 5.0.0 and 5.0.1-dev dockers)

### PR DESCRIPTION
**Pull request by TheToolbox**
fixes #57

### CODE REVIEW

**Comment by bradymiller** [comment]
your master branch is getting messy :)
(when you bring this in, rec using Squash and Merge, then won't bring in any of the unnecessary commits)

**Comment by TheToolbox** [comment]
I've been squashing my commits as a rule since I've been lazy about rebasing. Thanks for keeping an eye out though!

**Comment by TheToolbox** [comment]
Passed a quick glance test, merging it on in

**Comment by bradymiller** [comment]
Should have time to build/push it in 2 hours or so (if not then, then can do it later tonight).

**Pull request merged**
