### PR TITLE
easy development docker environment fix

### PR DESCRIPTION
**Pull request by bradymiller**
It seem like the easy development docker should use the local repo code rather than grabbing code from a online repository. Changed it to do that. Still need to build and test this before bringing in.

### CODE REVIEW

**Comment by tywrenn** [comment]
This is now of high priority to fix due to me not able to view changes.

**Comment by bradymiller** [comment]
Working on this now. Getting weird missing file issues on testing. I should get it sorted out soon hopefully.

**Comment by bradymiller** [comment]
I think i know the issue here and why the original author of this docker-compose had to go this route. When you make a shared volume within a shared volume the inner one is always blank, so then by grabbing the code from github, it would refill in these blank shared volumes. There's gotta be another way.

**Comment by tywrenn** [comment]
Found a fix for my issue yet it might be wise to fix this anyway.

**Comment by bradymiller** [comment]
testing well. bringing this in and building/updating dockers and the docker-compose.yml

**Pull request merged**
