### PR TITLE
patch guide updated for patch 7

### PR DESCRIPTION
**Pull request by stephenwaite**
copied @jesdynf 's nice upgrade guide and then edited for patch instructions, needs testing

### CODE REVIEW

**Comment by jesdynf** [comment]
This process needs testing (and possibly updating for more recent patches) before it can go in, and apparently I haven't gotten around to doing that. Will try to get there this weekend.

**Comment by stephenwaite** [comment]
it's testing ok

went to test with an additional multisite but having problems with adding a new site

>  Connecting to MySQL Server... ERROR. Check your login credentials. unable to connect to database as root 

do i have to open up port 3306 on aws or use something other than localhost on the setup page?

**Comment by bradymiller** [comment]
hi @stephenwaite , making new multisites is complicated since need to bring in some files and manual edits to setup.php. Here's an instruction set I sent to Jit awhile back to do this in 5.0.0:
```
The following scripts need to be brought back into the main openemr directory:
acl_setup.php
setup.php
gacl/setup.php

And in setup.php, you need to set line 28 to true and maybe line 33 to true (only do this one if you plan to clone one of the multisite instances to another multisite instance, which is not done very frequently).

You can find the above 3 scripts for 5.0.0 here https://github.com/openemr/openemr/tree/rel-500 and can use the following 3 commands to get them:
wget https://raw.githubusercontent.com/openemr/openemr/rel-500/setup.php
wget https://raw.githubusercontent.com/openemr/openemr/rel-500/acl_setup.php
wget https://github.com/openemr/openemr/blob/rel-500/gacl/setup.php (note this is same name as above setup.php but goes in the gacl directory)

And when you are done running the multisite installs, you then need to again remove the above 3 scripts (or else you are open to security vulnerabilities).
```
Would definitely be nice to have a docker instruction set for this

**Comment by stephenwaite** [comment]
thanks @bradymiller , think understand that part of it but remember having difficulty getting past the multisite mysql settings to avoid the 

>  Connecting to MySQL Server... ERROR. Check your login credentials. unable to connect to database as root

**Comment by stephenwaite** [comment]
cool, thank you Brady and Asher

**Pull request merged**
